[
build
]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[
deploy
]
startCommand = "sh -c 'envsubst \"\$PORT\" < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.template && mv /etc/nginx/conf.d/default.conf.template /etc/nginx/conf.d/default.conf && nginx -g \"daemon off;\"'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"